# Generated by Django 3.1.2 on 2020-10-11 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=50)),
                ('note_content', models.TextField()),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
