# Generated by Django 3.1.2 on 2020-10-11 22:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
